naming:
  ClassNaming:
    excludes:
      - "**/test/**"

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

style:
  ReturnCount:
    max: 5
  UtilityClassWithPublicConstructor:
    excludes:
      - "**/test/**"

formatting:
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
