/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * My CRM Service API
 */

export type GetProductListParams = {
/**
 * 取得するプロダクトの件数
 */
limit?: number;
/**
 * オフセット
 */
offset?: number;
/**
 * 有効なプロダクトのみ、または、無効なプロダクトも含めてリストを返す（`false` の場合は無効なプロダクトを含む）
 */
active?: boolean;
};
