/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * My CRM Service API
 */

export interface Product {
  /** プロダクトが有効かどうか */
  active: boolean;
  /** 詳細 */
  description: string;
  /** プロダクトごとに一意な ID */
  id: string;
  /** 名前 */
  name: string;
  /** プロダクトごとに一意な SKU */
  sku: string;
}
