/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * My CRM Service API
 */
import type { Product } from './product';

export interface ProductList {
  /** さらにプロダクトが存在するか */
  hasMore: boolean;
  /** プロダクトのリスト */
  products: Product[];
}
