/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * My CRM Service API
 */

export interface User {
  /** メールアドレス */
  email: string;
  /** ユーザーごとに一意な ID */
  id: string;
  /** 名前 */
  name: string;
}
